name: Workflow

on: push

jobs:
  first_job:
    name: Primer Job
    runs-on: ubuntu-latest
    steps:
      - name: Inicializacion
        run: echo "${{ secrets.TOKEN }}"
      - uses: actions/checkout@v4
      - name: Instalacion de node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Instalar dependencias
        run: npm install
      - name: Correr tests
        run: npm run test
